item = new HashMap<>();
item.put("name", "Es Dawet (1.5k)");
item.put("price", "1500");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (2k) ");
item.put("price", "2000");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (2.5k)");
item.put("price", "2500");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (3k) ");
item.put("price", "3000");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (3.5k)");
item.put("price", "3500");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (4k) ");
item.put("price", "4000");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (4.5k)");
item.put("price", "4500");
item.put("image", "esdawet");
itemsList.add(item);
item = new HashMap<>();
item.put("name", "Es Dawet (5k)");
item.put("price", "5000");
item.put("image", "esdawet");
itemsList.add(item);
/*
